apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tgops.fullname" . }}-secret
  labels:
    {{- include "tgops.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.secrets.telegramBotToken | quote }}