apiVersion: v1
entries:
  tgops:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2025-04-17T14:51:24.257074+07:00"
    description: A Helm chart for Kubernetes Telegram Bot
    digest: ecaaaf697247af2e11feadc33f224e77aed2a8e08e39a6d2a8116f394ed6f87e
    name: tgops
    type: application
    urls:
    - https://sergei-li-tech.github.io/tgops/charts/tgops-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2025-04-17T14:51:24.256637+07:00"
    description: A Helm chart for Kubernetes Telegram Bot
    digest: 61e1280da625b1479e107b3435d1814bb4e14b9343c66461065104d45a7512ae
    name: tgops
    type: application
    urls:
    - https://sergei-li-tech.github.io/tgops/charts/tgops-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-04-17T14:51:24.256217+07:00"
    description: A Helm chart for Kubernetes Telegram Bot
    digest: b42725e3d1d5c4a139e85607e9df091ceece0c29eb46f442eb98a3543dac658a
    name: tgops
    type: application
    urls:
    - https://sergei-li-tech.github.io/tgops/charts/tgops-0.1.2.tgz
    version: 0.1.2
generated: "2025-04-17T14:51:24.255675+07:00"
